### ISSUE TITLE
Fix Docker Container Loop issue

### ISSUE THREAD

**Issue by osobh** [skylable/docker-sxweb#2]
Please accept the pull request as it fixes the loop that the docker container gets into when started up.

**Comment by edwintorok** [comment]
Done https://github.com/skylable/docker-sxweb/commit/dd8cb0d168ab27a1fbd54ff8b701e35017816738

**Comment by joshashu** [comment]
How can we increase file upload size in sxweb running on docker? I am not able to upload a file more than 100 MB
